### ISSUE TITLE
Telegram.contact_list raises error

### ISSUE THREAD

**Issue by mllocs** [platphorm/telegram_rb#1]
I successfully initialized the application with `Telegram.init` (introducing the phone number and password) but when I execute `Telegram.contact_list` i get this error:

```
main.rb:24:in `contact_list': NULL pointer given (ArgumentError)
    from main.rb:24:in `<main>'
```

**Comment by platphorm** [comment]
Did you figure out a resolution to this problem?

**Comment by luyzdeleon** [comment]
Hello, i am having the same issue.

**Comment by platphorm** [comment]
Can you try the latest gem from telegram_process branch (instead of master)?
Also, before trying latest - please delete the old telegram gem from your gemset. Maybe even delete the gemset directory and run bundle from scratch

**Comment by luyzdeleon** [comment]
/lib/telegram_rb/telegram.rb:23:in `load_config': wrong argument type nil (expected String) (TypeError)
    from /Library/Ruby/Gems/2.0.0/gems/telegram_rb-0.0.1/lib/telegram_rb/telegram.rb:23:in`init'
    from test.rb:7:in `<main>'

Had this error when used the branch

**Comment by tsaifi9** [comment]
Ran into same error running this branch

**Comment by pahnin** [comment]
Telegram.contact_list would not give me the contacts list but just my number as a peer in an array.

**Comment by pahnin** [comment]
When I stop and the start Telegram again I get the same error as mentioned by mllocks
