### ISSUE TITLE
not available gem

### ISSUE THREAD

**Issue by beckmx** [platphorm/telegram_rb#3]
The gem cannot be installed by gem install ... how could I install it?

**Comment by jiren** [comment]
Right now gem is not released. You can currently use like this
Create `Gemfile`

`gem 'telegram_rb', github: 'platphorm/telegram_rb'`

`bundle install`

`bundle exec irb`

**Comment by beckmx** [comment]
yeah it looks it installs, now it keeps telling that the Telegram constant is not found

**Comment by jiren** [comment]
after irb command you have to require 'telegram_rb'

`require 'telegram_rb'`
`Telegram.init`
